name: Zip Files on Push

on:
  push:
    branches:
      - dev

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Create a ZIP file of all files in /src
    - name: Zip repository contents
      run: |
        zip -r lc-tracker_deployment.zip src
        
    #Step 3: Commit and Push Zip file
    - name: Commit and Push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add lc-tracker_deployment.zip
        git commit -m "Auto Deployment of lc-tracker"
        git push
    
