name: Zip Files on Push

on:
  push:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Create a ZIP file of all files in the main branch
    - name: Zip repository contents
      run: |
        zip -r lc-tracker_deployment.zip .