name: Run E2E Test with Puppeteer

on:
  push:
    branches:
      - e2e-testing-patch-1
      -dev
  pull_request:
    branches:
      - e2e-testing-patch-1
      - dev

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  

      - name: Install dependencies
        run: npm install  

      - name: Run Puppeteer E2E Test
        run: node src/e2e-test.js
        env:
          DISPLAY: :99.0