name: Run E2E Test with Puppeteer

on:
  push:
    branches:
      - e2e-testing-patch-1
      - dev
  pull_request:
    branches:
      - e2e-testing-patch-1
      - dev

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  

      - name: Install dependencies
        run: npm install  

      - name: Install additional libraries for Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxrandr2 libgbm-dev libpango-1.0-0

      - name: Run Puppeteer E2E Test
        run: node src/e2e-test.js
        env:
          DISPLAY: :99.0
